language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: Cm2VT5k+qUW7OkcNyG1dW8PTHATcIJA6x3Sk4CUVLUIVFGeMs7KdqDKdxOmXQVCYYOoZ9C6Gym5TrK+KYFpSX/XncZ+Huo94PYezmGP9ql8CHpTzBHGb3gxpApaS9WxZer3fkd5kEqgZLUxImAYCuHzXWAOgpSgK1+H4BrDED6KlC4MIhxSOtFef4JR65GnezTUMf8vEpRW49Li3IkokcKIDtiCfH9Ox07uh1IJJ5e6t1Ae5DtRYTX5PlArY4gh2qyGK5K7vnP9qvpE7P25Whie3+Iz2d3+Qov7ziFVdz2VcW9Su4WkxnEE6UfcDu/HX1rBJ2WQouBhwNmAUcmsKYuY+oHyXPGZqT/PGiX4+HLR1+FHV4/KLRFkQwRkQSUMXmRteyb4YtCoEQjdXVfEZjarPjQcqcAx+W8R9b00cb26Ib8hRLj6wsweea1pWBAAlHeAd38ug8qjlXrouodxcawMQjrBg/BH3NnaVjBepqiMFHZj1qTtMT54hZhvRgrqw/eRtoQwiHkczYqDfh9uqS6MxLA82iaiymgCDgF3cffxf5fsaGko7onA0xqtql0UI8h9loYyuC/OO+BdGe0hmEChy0RlGg37tSaU0J1WWdZ363POchmKFJwv6fxw5pgXc1HXPBGaB+MHPR10y3DFo5qjJlHuim8MTMfWlheU2GRs=
  - ATOMIST_CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: LyoXkUHaysHx8wHW85YlITGH+H/vly9zYS3mJV2WgFNL6yVGjJVpC+uo+af1Lp91OPjWrOUPpeH/UY9+BCgbrIif9Vd0Io8CIn4b7yOFYhCY/cgqKqUVYlB9qPpAvduPszDFFx+NPPvC//LDAbyzQXP478bcSRDgvtRYE+4PbdMBPyEecreV5Ad3kZ6CCmyD3kpTM0/8EqfZ3nfK6eDIki7asfoK0IY7Q2lrHdeRIA8kTD7Iuz6Q4Tn53QpXnqaahMe2lCfF8VfeBLcglNsv3qw1n+SM/Sgze7uExNw0GeTuCaCwRz5wG2GnYbKYwTEn5ln04+LBhxF+8fUYOPDO4EiHwqrtVXNlnOh//9xYCIqiZfLX/8iu2JHLOOeiJCvGImOyv963YhgZClrnE6Y901mbZckJnYRjIot04u+UHuEkaCegxh8RpEiCPGds9HZwRZt2LaPd5Sp+JnMkRNN0dgnWmv5TPMjTZPHJiXe7TGRiap1BrVv1c/KxpmLfQcTfAWB4bEzw1zKn1IauDnL7d7xhmwqBB6dRuvWnN2i9kG5tGTAC+k4u2RtReBbGXOlZNlqJ+YBE7sAl0eRc/HhQU1EYo2oLVzKUBajRAyEYDvJQRcCTt3f4DjB8gEAqZ4qu8WPpnFgBJkFqJqN2bbs9FKJ6hRYasanUJgrir3O0jDU=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: RhdxMsFNZXiOQp5NpSIutAOFCBlGKBfreiFfDQ+Ll/Lujjdx5pu3dR35nMZSilSo1TLu1pudUtN72awXRs5gpkSscMBAn/3VHOKkYpHAJY8VA+5D3SWb3pmIl0JXeuy5mMxyS8zznCgXm17GiQpy0pam55z87BCXWj3Ji/mkaREPNGTl+32apVsWB5gRcNRnjVI3q9GB822C8T7rIkmAI1gXtGVBj8ANddn9m9UCX/viGyZG9jvhkQG+n+9aWnofTfp0XWYb2OPV+BAxqPFm4289yLLH8lUqq49RDePdvnb/usCEj1qT/Pt8bhU5esof9mM7M1rERtrIxS0WLUJ4zEvC9P/lXP9cGc01lqmRAe9hiibxUqL3ajdTYG+RII6OfX+C2OhI4AmX7GyhiafhvRM7xMU4tZDUM/1puZqBF/bJj85qkku+G2t3XrK3nYFHl0QBq4D2vvJJWDLXWKG521f8ZgG1/e5RaxJc703r41VvNMTrPCOCwtWQlaj5z5nBUUueYEqT0hBd6mt8rAIl1hxwk7XH/t6d31FLOAlKpkC4/Ov7irXGqKJh563JEP6HGqvi/lS9STvtNRz/MQYhG66BxwpJjF2eAfVXASjTec6IpiDXb46j+aVvch5dU4qllmKyJ8p2lZxT320X1ZfGGycXOBgkIsz26zmlJGe5rUw=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
