language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: PX9MYekaSJnTnYneNEnvTi1gpLPV+d8/TEsZF96Mo24Rb90YRNl9z6LgfiKRnAGHyQG1CP4MMNvtkBwx2KRFs7S1VWq1gOpSXfXKUdTgGYSIO8wyPtkcmmWttajX22wNN0/NyTGAop/RCyP2o3HfOlnHKgUIopRGpfx/RquO7qOflNG1Mt3EZoXAyYJ+LRq39OAegcf6dVP5RO623+khgyM62NnrtEAWeYgbVsZSw7DMuU0ZAg5c7piyCr/Vkpj4rSlcZEySWVWVOUJy4ACK9P/yTKnbOGYSAJcHSoQ76/Cwp5pwktsFlrXdNa0HG/q971Z9UvVZtuwtuuPg4f7Q/Xah0VtYwRC3bvcCIK/D8nKUK7X6SEuf9H/2JTjroIQp/xyv6kjY83oBt+9Tvp/V6WJvGc3fCOFITaRx3cvG2Ep0TOoaxRPyXE6SDeU6lyMfIVv7KnPf7L/jfMCSe7RRG8FRgoR8rZT85BI45K0ZzjWMVRcZ5vWq742ipbNvmlO6yQx3rF5Th50IuwuKFNdnyz7cqniePP6Qy9yP8LDtoa68rimRQuKF4TLbD04tsO5UeI1U3gRZ7kQEwgavBmzSk4Ol6f/EZR2DQwev04xKNbFwS9v6c7xPP4NYG5MRHE8ruoOOWuV10gNNE7QNPS0LX4o7GTCnwRPq95maeCDf8Rk=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: RhdxMsFNZXiOQp5NpSIutAOFCBlGKBfreiFfDQ+Ll/Lujjdx5pu3dR35nMZSilSo1TLu1pudUtN72awXRs5gpkSscMBAn/3VHOKkYpHAJY8VA+5D3SWb3pmIl0JXeuy5mMxyS8zznCgXm17GiQpy0pam55z87BCXWj3Ji/mkaREPNGTl+32apVsWB5gRcNRnjVI3q9GB822C8T7rIkmAI1gXtGVBj8ANddn9m9UCX/viGyZG9jvhkQG+n+9aWnofTfp0XWYb2OPV+BAxqPFm4289yLLH8lUqq49RDePdvnb/usCEj1qT/Pt8bhU5esof9mM7M1rERtrIxS0WLUJ4zEvC9P/lXP9cGc01lqmRAe9hiibxUqL3ajdTYG+RII6OfX+C2OhI4AmX7GyhiafhvRM7xMU4tZDUM/1puZqBF/bJj85qkku+G2t3XrK3nYFHl0QBq4D2vvJJWDLXWKG521f8ZgG1/e5RaxJc703r41VvNMTrPCOCwtWQlaj5z5nBUUueYEqT0hBd6mt8rAIl1hxwk7XH/t6d31FLOAlKpkC4/Ov7irXGqKJh563JEP6HGqvi/lS9STvtNRz/MQYhG66BxwpJjF2eAfVXASjTec6IpiDXb46j+aVvch5dU4qllmKyJ8p2lZxT320X1ZfGGycXOBgkIsz26zmlJGe5rUw=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
