language: java
sudo: true
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_REPO_USER=travis-mvn-deploy
  - secure: PtHUEmEppek1BT6ZRVjVO4Hu0DR0IH47Mgyq/ZNKAYFydWnJ/hmB2xm3LKNuDF/QUq+n5G28tN+nlKdAIJTZl9NRQeh/dAxkXAFo2dHkprOuQvhT29ItJRb7TTHs5Nbz5IHz2EmjHj58WjvulQs+OctXvSbJtuSp09Zb3oQFFGa3nTEUD053pbQSpfLP5BxaOUvNCez+XU7WQ8UBd9Tq5tLflbzGxzD/NtiiP7uHgQid97myVaRv04at/hPIamRoZqa1WjW0J3bq2y7b36MZsDhKDsAzkYoXYx1lyewpCTt1Y5K83gyBlAXp3JpifebPhyl5KctQQoEiKqP1efzSGwp07QwW0faBANlOv3LWbPhdc6kMmbpDu4CqjH00Kzg/nHWOF765HUK+LNrX4Bv89ZKllMpDZZo4YLnOcajsKXBO3MyYyv3ShBkrMqQjQ12/G2gZ8fHG5hUci14cZsZQJDSGk6CE6fvZ+TPR/x6rYTIOZ4e9hjLIQo5h1fXbFkvTd4OJ8VGWKDCuv8+u9cA+LIm1v0+OeFueyqV3bn4GtWmc2hFbxaUKO4Kj8DgCHXOmYcpCUWsOwwAWOv4J+eIuk+YrffWZBy82wa9KjbOS9N9mVfG0X00mepF6WNgx6HahC6EAnYr+hbCyaXKiVPF1PCjeDqEYRQayY7tjnGjbB/0=
  - secure: sT9bjbk4HAUZ5x8EOZqapAqIMbSkjsrS3Bn2HSiZPCuLN8qUOAdVSc7Nu4bNH7Ofb+TJSw/bybNv7N14UOnK86IK+/zUzR1OHayTS54KJSuw2XabaWXfOciRNtjcjToPnlOktCjYHtlRyzRrnkRlIrfp/Vb2lvcAH85OBNObS+L/Qin3UEj3m0DP5B01mAtXeK7PgrDpo7UcekngRD2UGgX312egB1ehchk6r7uti/GXUnwr/hAmaVq6zFSs6Q6MHqxeA6NrqkZGdqrSt1ZNCYGu9uBDBVLxzKvXS0ZEC/JRfv2BjfrAwZJkUWzCKrVHfn422s1kPTW9v5dJmMZxiMKTJefSk1nKRiE3E2KJVN3zSrCC5vncMOo/JxmXzGKLPxksEBbOkFko1TZ3dClp8KdeKpLwY7/6Hs174jfucCFRkvobk2xE1Z/oJ7S4R6gixkGmVZYo5wGE1UPBqmr2MVOOV/P2I1+2+qPs5TGXwuPJeN+rkyCkzum4yKHAGtraC9gqw+BPwtl6VurWqqf+r3Knz+F2jUe3zvPXBXgs9lP/4+kMTYGjStKUK5xXjpIWntTBW9gRb8Ae5mSwUqhYVGyLjeS3SDRGHBVguWGCJwYy30i8PSm7JTVSqFvO9SfVHb/g1XWOOteaBuC7KcTOKOekFIxZSl0pn4OzCyWKmL8=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: deidUzd/Dlvw9O1FtEDK5hDO6gkE35aEnCQpNLHjSsvZ11rrBe12XFRBp3Vh2w+YrjeiewYgZYgyqc+0U1NFkk5dE/CwrCnoUf2NJ2qrJlELFtaMb/hVck70Egp/ZM51tjG9nSFNv5D/0mFe+5IjNp5wMYMJklK3JSnEKllum8m7XI9CnIRJgaHcSII1Z9tLEyuIr7v0iL8kZWiM0STsRuR4Mnxi6cvUpyzoEIiYpHSUnRwZDd0FWDP3Onyn9DjgFBEmVDPEnzQuNNJwWpyjNr7ZLn1M0RVGju5LtpQKoi6lwqqkNjX4argnN7C6nmZLyhOD/LdB2MBX2Muh17A3ioU7Zem10K5EJXK9X4ymLa+wBBgEYTfe/9bEd6OyDcX3yQZozt8XAoJ4DxUSMN5jlFw9usj3habvKkfxnMvR6Gu+zz2Z948zQYuAfOf5U6Ers1dbD+KB8j4D6J/3RPdrkzm1GKGJ9IbkqWqgHMge9pS67bqLHA3dzb0TLAi5vjKsj3EXxL27fsu1uQkok/KKlyyBfHEHp02AmuaqORyfjQyRElcFGtNJK/SLDuLRcb6TsDHN5LWQrY8+uyjymJXOt7lVDw9JZXqMP+BvG/KH+ASqifrBNirRYZyLHC6ItqNe4RnHmlGcHvagztbHsiFjfOXIJX4eUzAX7hS5cEnsdPM=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
