language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: tEhsv37LYIJVfEBoctI6UOJ+O2EHPvKqwzVzH/154E7p/yZ1Yaa/h1w9a4rtd63HWJNFpox3OvgkfXm2P3Wtd6PwUTRZWaLUQQycOcsX5/pLYKjp2cM3FkiJQE7a4IYkdXTXr17kEd7yNvFvwP6NzaINHC79xM370HGnd6hJm17rPLul4p/EwcaUAClKTYK1GldmpiPQYWrRZ03keiQ5vaPih+K8ZgGS3tbxZJ8AHaLxuPMiMXxvCINb1p8DitYA2r1AcRAJTElzRMvvELVqF6zSF4HTBI9rjDuJ+jYenfQpgVziC/kSvhj0opzbhkKRxZCtzwJjRWB/ZfUCxFrGhWVAOT9mvbIiMbQiPjJdk7pq+aJ18oDBMpqegd0649Vmdp3/snhLvBMppLNOBGn8aRVdm8GVqoSPcrTtPSCK6SDwOxQvCOZMwIOeVLENbHMJzZESuwdZ1IYpwO+FDKY+3kfjilG0FTvj4BmeOitKRscFYH+S4NU+cFI50hAgp2+nb513ON4EhNh6cq4wE2+r0+ChE73qoRhpH5LSrtu5JQIEb7tlG5JR4JlitbjxV0DYap2HCOoXskjGl2a+DFTLkOgGCy/uCHhrKG7iM8XL8qTaeVasXrU28ywbfE6e1gduoMtn2AIMzKUTe6C2DficRApi+A6lqyfuINXk89sGQj0=
  - secure: YT8VhXs4PVPeNqcHgULdYk3xtR2EIcNPMekCOSSEGqeOkyr8TooeByhZ0mlq5KEQPzTzx+x6YVHJsrpiW7VKiKaxP0lQN9nN3osfkDKbWr2Z4KO7L7oaQvPMztXgwAtnhh1+o1hUZKzZQZD0sVcbz325AuYG5fjaTmGDkmpyRaxnztY4bql6h75/+NFNZQotBLA1x1WtSk023aaUuqB0rfgYtLWN3t61cmL33JW8B5PBF6dY9pjGfygZPEocE3UwxuazgaSGKlg6d9o/wcot6xjYZEYr3QHOMTULhWngJlO0cJJLkRHPltNqXAr5whxRPNAL6IgaNOPyQP2DkUqRWBNKtJvWFtvmkioPLP3WUYGfa1QOTuJfDuacaYuI5Z762XTbmBeZxlTiAygbNIr0b3ZE9mHOoxUFQbmjwUwZm85G1XmodgzJPxueInv1ZiJk4mFL3TSVnUvs+xHRg8babjimYN+SSudwlgUcRZHFH+QQoIZDfv0N+wtSenQQ72JLqRYUMB1VIsPROki8YVwkofeM+kEamk9BecSoXxvsGa9UUV9XI77wK9S3kYgpd2VdJMIsZwoTrlQVIGER7vQeJo5AIhIjiOdcntt90lUHQbhsCi9G6Vjs2Pbi9FV4bp8Iydgib2B0Wb5uJWMso5KjhkQ86hZ9wUyKHTIGWGmHQkY=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: Bk+ppVx1cO4gs+sPPD+lrFbBYscluKEonFIqfZnXviAnJ3vSrFzn9kSdoTJOLVxkkip4PT5JCnfv5qoA18TPYsben4oKDLlkhJiYyDm9l3JP48hxGD+F5Pe9aFKOk1sHAbhm1sFKwjvt8TPzODdOpadrN6hsQDF+Xal7DH5Ky6kQB1MZSqsg0XZ/F4FWMIDurL2qJ8YPkE+auvV/0vIdCfHykZHwqF4/hrZVYMPXJCYjSYk2TTLOP96GYStKEYsmWMSLVN9dEbBrJUHwKmmGNpjd+E/QLfq0VRIKJLuqX5TSX9r1U4WIGHYEw+0HBE/97vnqPfJ6tYJuq58FoECjhLtsHyj3fbzkyaAKrCkbeG8R/BKa0jszhmjAJal0GH0V5DrurNAkESAFiPG6P9cixr5039exfCXBv7kaf0BzV/La4HMqNmIhnf9wEPltHf3Jq/E1raLcQHq+b+lWFAguqpZtqKGoslK98SKuJD31TAM/LdZkuBhfQlJhZq+VgcGK5ewpOfeZXSum+CZNgOvbRWQsRtpUb8NLWF9QGyxqpKNTdOLowISjXfAw9iGADl6JNwl3vu5paiO1h7U+9VTXgRsbHylz6HsZ+ZdaX7wRyQNmY2hSi57dmqDNDTQreLribnlCmMdip4n3JHUpvNPQJfp7pIcKDf6IqGKn412GzUA=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
