language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: vveqvQ/nzQfQrk0egW/pwUYDzm+gKKKafcQC6swBKDqFbnT5IXa8mZ+0+0IC0kpsrWzaw6duagDzUUmRcmvs9loFhrJ4S/8eYP81iZfnTI2Ocp/plxts7dElT4+OIdKLJGPl+GVHoAtisLdubHzWiBvA+Y6RqoAYQfgv7HKOnpid0XdBWdOrYM8jUmSFZbX98XBVGOCN4dWUck24gWEy/csnGIJ6eY0vQdIR5Htb3gkLVcMxYnQnQkKmlOpUdNyyvgO2MgpEW744vY79Mm18tmyNdQZk3iKW8jEHeJVfvA4cYFRQ4a99C85baKpOPY0A8NtiKht3yT0BGBg74vfXb32WPNVSJ70XsuDWTb0h1qpVI3DA5mFcWqJBdzD2eTrTh4IbOuxD3i9I9N6bPVKGUJiRnTTWiogVhHVoM9cpDOBrLiIK5EPm9N3FJ91S01t2qjGU7wVf6Nd5PEyDezfD9iiaDgDM41fAQysxt3wPjsnrOxuT9/3jbEojq42Y1CQMj/g079jR71Yl0bWOZFgnY5WiJGhpaaJkgkr6NCicnITfeXbmKcHTef2JeD3bMUjF6XgfuPyJdG5k0FZOGYWyMMTOKUWsNA06t9MPWoIngZyNB4DFR9IKYjERsifonSlLxUzrzExoStSYwoDEYyQONUW9zoBFgrL5Am/tG6HgGGs=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: RhdxMsFNZXiOQp5NpSIutAOFCBlGKBfreiFfDQ+Ll/Lujjdx5pu3dR35nMZSilSo1TLu1pudUtN72awXRs5gpkSscMBAn/3VHOKkYpHAJY8VA+5D3SWb3pmIl0JXeuy5mMxyS8zznCgXm17GiQpy0pam55z87BCXWj3Ji/mkaREPNGTl+32apVsWB5gRcNRnjVI3q9GB822C8T7rIkmAI1gXtGVBj8ANddn9m9UCX/viGyZG9jvhkQG+n+9aWnofTfp0XWYb2OPV+BAxqPFm4289yLLH8lUqq49RDePdvnb/usCEj1qT/Pt8bhU5esof9mM7M1rERtrIxS0WLUJ4zEvC9P/lXP9cGc01lqmRAe9hiibxUqL3ajdTYG+RII6OfX+C2OhI4AmX7GyhiafhvRM7xMU4tZDUM/1puZqBF/bJj85qkku+G2t3XrK3nYFHl0QBq4D2vvJJWDLXWKG521f8ZgG1/e5RaxJc703r41VvNMTrPCOCwtWQlaj5z5nBUUueYEqT0hBd6mt8rAIl1hxwk7XH/t6d31FLOAlKpkC4/Ov7irXGqKJh563JEP6HGqvi/lS9STvtNRz/MQYhG66BxwpJjF2eAfVXASjTec6IpiDXb46j+aVvch5dU4qllmKyJ8p2lZxT320X1ZfGGycXOBgkIsz26zmlJGe5rUw=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
