language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - CI_DEPLOY_USERNAME=travis-mvn-deploy
  - ATOMIST_CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: oN9XI/gNJxUNUzfTbY8lVj5Vuwu670peUBpVu5iJW4pvsO9vHYo48kBYMAS/8uHSmJEXb5Bj75R2xgg0ScLpEEqAAlDpLNh4oXehQExRH/G23sfzyTUC2BpP8XdtfFlfiGj1R9oaGqz01fIjRgKPHQWDmDanefdlqt3eoYmXACeEOGkAOUtlJ/JPdQwkpGTA9U+LrwjgyjFB6eQ6WM1PIo9yn1zer9rEXuYaJs4rmaICnLJI6l6xI7CpOmzNrJIwKen6USGNhzvypC/Zjw5kF7cYaKpzX9I9uCA0t9urGi/9JlYyN2VXXTPLOMpErSHMiKTwfwq/8blUBkUiHewsPOJ/YveCzkB5cA/skDvygLC5g+3YGGrzmpLHrkqObE3F62XidtK57k8MtDtRnDGILTs5X9O34Vy/T9JDDN5JwlLNwNX6Tfjr/dR4y6WT93sa93J15gLIxcq+Z9M/9QCh1DRKgb0qqzPR3D4rWePqvXQQbKPZyondxafYPz0J7p0prq16BnNAPdvT5PXc5dI7aN1G14IFendX6pXPyoHuJo42aPNT9Jrb+o3Pl8+VPcWU+qNEKtlegIhhtYLighSIuxFtzuqhCOWadr3+EZa0v0ieKG+nlqb0k8VqwvUju5/zuifMwRhyOt9Fc5c5c1++WIGPim3nUfZem4vmNqLd/vE=
  - secure: R6QdIQbIseVLLa7JRjYAlANtr2MI3elBwBNODdEswWC+Ng76YGRklrjs17jEatcDMzUXLnmZLh5G7X7T0s1jRvNtvyze4s+1yofPPc+6Wd/+6fEXgO4KgryWUBeTcNRPxdfx7ctexGB7zdOr7p0TwYhXWs2OqDiVAqsIzf2/HMha/NiLu4IMnl6A6nPqh0BFjMqph+94HEKf+mgZNWJmS5bMQi1qYajIisJph4k6I9suh4ogQPfP6/v8VWClanS9SJenpM9J9i6VJlKSirMa0j/Vkpc4Yp1i0FT+PotvJlhCyBUOAKKBi+BUAwnq405ap9Sn5tasS62jXEgaClDxq3vdiIx9xnF8HQ4L1q8kqj7Y6OXH6pUz2TuNCFsEzH7MSpiQaozyGsjBf+kLVjOzXbkScTDcUC5qApI9AvQowiebnK9kI0CTCPQWs+D3mA3CyVXsjpYvnFRHVMcGnZ6pmk/7PS3hKDwsavYtKhgCjzx3MA9S8qNOXHmzkAUOyyo3dPpTVbKj/TaWqapO3pZ+X05yF+mmaHV6V8QW2AutQuW+gJRaUt34UuESsdp3lNJdrCWN5HKxkhltvCZ2uSJZtyRS6tC57YIR+NP6IvimfPwfSaZ8UA0YPheVq3th+on/2KjnedYI4I6PCzA41ua0nsWovgjETsqyo2gK5s6z/yM=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: RhdxMsFNZXiOQp5NpSIutAOFCBlGKBfreiFfDQ+Ll/Lujjdx5pu3dR35nMZSilSo1TLu1pudUtN72awXRs5gpkSscMBAn/3VHOKkYpHAJY8VA+5D3SWb3pmIl0JXeuy5mMxyS8zznCgXm17GiQpy0pam55z87BCXWj3Ji/mkaREPNGTl+32apVsWB5gRcNRnjVI3q9GB822C8T7rIkmAI1gXtGVBj8ANddn9m9UCX/viGyZG9jvhkQG+n+9aWnofTfp0XWYb2OPV+BAxqPFm4289yLLH8lUqq49RDePdvnb/usCEj1qT/Pt8bhU5esof9mM7M1rERtrIxS0WLUJ4zEvC9P/lXP9cGc01lqmRAe9hiibxUqL3ajdTYG+RII6OfX+C2OhI4AmX7GyhiafhvRM7xMU4tZDUM/1puZqBF/bJj85qkku+G2t3XrK3nYFHl0QBq4D2vvJJWDLXWKG521f8ZgG1/e5RaxJc703r41VvNMTrPCOCwtWQlaj5z5nBUUueYEqT0hBd6mt8rAIl1hxwk7XH/t6d31FLOAlKpkC4/Ov7irXGqKJh563JEP6HGqvi/lS9STvtNRz/MQYhG66BxwpJjF2eAfVXASjTec6IpiDXb46j+aVvch5dU4qllmKyJ8p2lZxT320X1ZfGGycXOBgkIsz26zmlJGe5rUw=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
