language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: tEhsv37LYIJVfEBoctI6UOJ+O2EHPvKqwzVzH/154E7p/yZ1Yaa/h1w9a4rtd63HWJNFpox3OvgkfXm2P3Wtd6PwUTRZWaLUQQycOcsX5/pLYKjp2cM3FkiJQE7a4IYkdXTXr17kEd7yNvFvwP6NzaINHC79xM370HGnd6hJm17rPLul4p/EwcaUAClKTYK1GldmpiPQYWrRZ03keiQ5vaPih+K8ZgGS3tbxZJ8AHaLxuPMiMXxvCINb1p8DitYA2r1AcRAJTElzRMvvELVqF6zSF4HTBI9rjDuJ+jYenfQpgVziC/kSvhj0opzbhkKRxZCtzwJjRWB/ZfUCxFrGhWVAOT9mvbIiMbQiPjJdk7pq+aJ18oDBMpqegd0649Vmdp3/snhLvBMppLNOBGn8aRVdm8GVqoSPcrTtPSCK6SDwOxQvCOZMwIOeVLENbHMJzZESuwdZ1IYpwO+FDKY+3kfjilG0FTvj4BmeOitKRscFYH+S4NU+cFI50hAgp2+nb513ON4EhNh6cq4wE2+r0+ChE73qoRhpH5LSrtu5JQIEb7tlG5JR4JlitbjxV0DYap2HCOoXskjGl2a+DFTLkOgGCy/uCHhrKG7iM8XL8qTaeVasXrU28ywbfE6e1gduoMtn2AIMzKUTe6C2DficRApi+A6lqyfuINXk89sGQj0=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: RhdxMsFNZXiOQp5NpSIutAOFCBlGKBfreiFfDQ+Ll/Lujjdx5pu3dR35nMZSilSo1TLu1pudUtN72awXRs5gpkSscMBAn/3VHOKkYpHAJY8VA+5D3SWb3pmIl0JXeuy5mMxyS8zznCgXm17GiQpy0pam55z87BCXWj3Ji/mkaREPNGTl+32apVsWB5gRcNRnjVI3q9GB822C8T7rIkmAI1gXtGVBj8ANddn9m9UCX/viGyZG9jvhkQG+n+9aWnofTfp0XWYb2OPV+BAxqPFm4289yLLH8lUqq49RDePdvnb/usCEj1qT/Pt8bhU5esof9mM7M1rERtrIxS0WLUJ4zEvC9P/lXP9cGc01lqmRAe9hiibxUqL3ajdTYG+RII6OfX+C2OhI4AmX7GyhiafhvRM7xMU4tZDUM/1puZqBF/bJj85qkku+G2t3XrK3nYFHl0QBq4D2vvJJWDLXWKG521f8ZgG1/e5RaxJc703r41VvNMTrPCOCwtWQlaj5z5nBUUueYEqT0hBd6mt8rAIl1hxwk7XH/t6d31FLOAlKpkC4/Ov7irXGqKJh563JEP6HGqvi/lS9STvtNRz/MQYhG66BxwpJjF2eAfVXASjTec6IpiDXb46j+aVvch5dU4qllmKyJ8p2lZxT320X1ZfGGycXOBgkIsz26zmlJGe5rUw=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
